### PR TITLE
Issue 1303: FOV legend to display annulus/aperture based on chosen optimization

### PR DESCRIPTION
**Pull request by IraLeeBell**
Updates: Legend in Field of View now only shows annulus (in lime) or aperture (in red) depending on optimal method chosen when exotic is run (aperture photometry vs aperture photometry)

Impact: small update to exotic.py when plot_fov is called, update to plots.py for the plot_fov function including receiving opt_method so we can declare the optimal method from exotic.py at the time the function is called

### CODE REVIEW

**Comment by IraLeeBell** [comment]
[Qatar-5-b-green-outer-circle.zip](https://github.com/user-attachments/files/17138946/Qatar-5-b-green-outer-circle.zip)
[Qatar-5-b-red-outer-circle.zip](https://github.com/user-attachments/files/17138947/Qatar-5-b-red-outer-circle.zip)

**Comment by IraLeeBell** [comment]
The above zip files show the images_output folders for the lime green outer circle, and the red outer circle (the current state of the PR) when aperture photometry is chosen. If anyone needs the actual FITS files (and darks) please ping me (this example data set that produces the aperture photometry optimal method result is 500+ images @ 33.6 MB each).

**Review by pearsonkyle — COMMENTED** [review]
Looks good to me

**Comment by tamimfatahi** [comment]
Hey @IraLeeBell! Do you happen to need any assistance on this to follow-up on Kyle's comments?

**Comment by IraLeeBell** [comment]
> Hey @IraLeeBell! Do you happen to need any assistance on this to follow-up on Kyle's comments?

@tamimfatahi @pearsonkyle - I will work on these changes tomorrow morning (10/3/24)!

**Comment by tamimfatahi** [comment]
> > Hey @IraLeeBell! Do you happen to need any assistance on this to follow-up on Kyle's comments?
> 
> @tamimfatahi @pearsonkyle - I will work on these changes tomorrow morning (10/3/24)!

No rush! Just checking in :)

**Comment by IraLeeBell** [comment]
@pearsonkyle - I think this is probably good to go, provided that you're happy with the layout of the legends. Here are examples of PSF Photometry and Aperture Photometry FOV outputs.
FOV_TrES-3 b_9-26-2024_SquaredStretch
FOV_WTS-2 b_9-23-2024_SquaredStretch

**Comment by IraLeeBell** [comment]
Full output of each run in above examples attached here. 
[WTS-2-b-PSF-Photometry.zip](https://github.com/user-attachments/files/17250558/WTS-2-b-PSF-Photometry.zip)
[TrES-3-b-Aperture-Photometry.zip](https://github.com/user-attachments/files/17250559/TrES-3-b-Aperture-Photometry.zip)

**Review by pearsonkyle — APPROVED** [review]

**Comment by pearsonkyle** [comment]
The code changes look good but please pull into the `develop` branch

**Pull request closed without merging**
