### PR TITLE
Adding in new alignment method

### PR DESCRIPTION
**Pull request by tamimfatahi**
Using Discrete Fourier Transforms (DFTs) to account for pixel shifts using [imreg_dft](https://imreg-dft.readthedocs.io/en/latest/). Will be fallback in case `astroalign` does not work properly.

### CODE REVIEW

**Review by rzellem — DISMISSED** [review]

**Comment by rzellem** [comment]
@tamimfatahi - can you please review the conflicts and resolve them, if necessary?

**Comment by rzellem** [comment]
@jpl-jengelke - can you please review the potential conflicts in requirements.txt and see if we can merge this into dev or not?

**Comment by tamimfatahi** [comment]
I updated the branch

**Comment by rzellem** [comment]
@tamimfatahi - what's the status of this PR? Can we merge with dev?

**Pull request merged**
