### PR TITLE
New alignment code that does not interpolate the image

### PR DESCRIPTION
**Pull request by pearsonkyle**
Idk why the inits file is showing a change. I copy and pasted it from the dev branch.

### CODE REVIEW

**Comment by pearsonkyle** [comment]
A new image in `temp/` is created to show the tracking. The new image is a co-add of every observation which shows how the star moves over time and there are some lines to indicate what the tracking is doing. 

image_alignment_HAT-P-32 bDecember 17, 2017

**Comment by tamimfatahi** [comment]
I believe it's because you put the inits.json in exotic/inits.json instead of the main directory

**Comment by rzellem** [comment]
@pearsonkyle - please pull from dev and resolve conflicts. Also, please move inits.json to the main directory rather than exotic (see @tamimfatahi 's note above)

**Review by rzellem — APPROVED** [review]

**Comment by rzellem** [comment]
@pearsonkyle - I resolved the conflicts for you :)

**Pull request merged**
