### PR TITLE
Decreasing Memory Usage

### PR DESCRIPTION
**Pull request by tamimfatahi**
Here is the memory usage of EXOTIC that is currently on develop: 
Original

Here is the memory usage of EXOTIC after removing the scaling feature, which was scaling from `int16` -> `float32`:
full_reduction_no_32

Both are complete reductions. Also, scaled-down airMassList from `float64` to `float32`.

The big spike you are seeing towards the beginning of the reduction is where we open the FITS files and append them to the `list`. You'll notice a huge drop once we convert those `lists` to `numpy arrays`. Although `list` is great due to how fast it is when appending large amounts of data, it costs a lot of memory. The increase towards the end is due to the nested samplers and how it causes sudden drops after iterations.

It's also interesting to note that time did increase with these additions. Might need multiple testings on complete reductions on that as I closed PyCharm during the second run. However, I did run the beginning portion of the code multiple times leading up to the alignment and the usage was consistent where it would utilize ~600 MB in the original vs. ~400 MB with the scaling taken out.

**Edit:** Also, it seems like there is still memory left towards the end if I'm correct? Shouldn't it dump to 0 MB when done reducing completely and exiting EXOTIC? 

**Edit2:** Went ahead and deleted two of our largest arrays (`allImageData` & `sortedallImageData`) since they hold data from the FITS files right before the nested sampler. You'll notice a sharp drop around ~250 seconds, which is where the deletion occurs.

final_complete_reduction

If we can find a way to open the FITS files properly (issue #403), that would be key. The rest should be up to garbage collection/organization by separating these key portions into their own functions. Right now, I'm simply deleting them from memory and hoping it will free memory space.

### CODE REVIEW

**Comment by jpl-jengelke** [comment]
Memory usage may not drop to zero immediately at the end. There are some tools in Pycharm that are loaded into memory for the analysis and runtime, plus module imports. The trick is determining the overhead. If you write a simple app that prints "Hello World" 10k times, the overhead will be clear.

**Comment by tamimfatahi** [comment]
This was done inside the terminal. Would that cause these issues? Interesting about the overhead though. Would adding a garbage collector in the end help?

**Comment by tamimfatahi** [comment]
**Update 2:** I went ahead and overwrote `sortedallImageData`with `allImageData`. It seems though the deletion of the `numpy array ` does not free it from memory space. When `allImageData` was deleted in the prior update, it was a `list` that caused an increase in free memory. 

overwrote allImageData

**Comment by rzellem** [comment]
@tamimfatahi - I would take a look at how we deal with memory when reading in the fits files - I think we use the `del` command, but I would check EXOTIC and see if that's what you're also using or not.

**Review by rzellem — APPROVED** [review]

**Pull request merged**
