### PR TITLE
Temp fix for IERS data issues

### PR DESCRIPTION
**Pull request by jpl-jengelke**
Issue #1155: Add temporary, modified and limited implementation of barycorrpy until IERS data issue in astropy dependencies is worked through. ...

### CODE REVIEW

**Comment by jpl-jengelke** [comment]
@pearsonkyle @rzellem Please test. Please feel free to make any additional changes deemed necessary.

**Comment by jpl-jengelke** [comment]
Related to #1155

**Comment by rzellem** [comment]
@jpl-jengelke - can we close this PR now?

**Comment by jpl-jengelke** [comment]
I am closing this PR, unneeded due to root issues being fixed directly.

**Pull request closed without merging**
