### PR TITLE
Issue 272: Improved Plate Solution API and added in LCO band for filtering.

### PR DESCRIPTION
**Pull request by tamimfatahi**
Added a safeguard for plate solution using tenacity and an extra LCO band as requested by Michael Fitzgerald. Issue #272

### CODE REVIEW

**Review by jpl-jengelke — DISMISSED** [review]
Looks good. Great job defining the retry exceptions for tenacity, especially I notice that you've used the base classes for the range of possible exceptions. There may be some experimental analysis to focus on any other exceptions that pop up. OOP looks good, too. This is a relatively impactful change, so please test this thoroughly.

**Comment by tamimfatahi** [comment]
Might need to hold off on merge. I do have a question, but I'll need to discuss it tomorrow and fix it then.

**Comment by tamimfatahi** [comment]
Updated. Works great on my end and added an extra safety net.

**Review by rzellem — APPROVED** [review]
In @jpl-jengelke I trust.

**Pull request merged**
