### PR TITLE
v0.45.0: updated install/run

### PR DESCRIPTION
**Pull request by rzellem**
### Features
- Simplified EXOTIC installation and run

### CODE REVIEW

**Comment by jpl-jengelke** [comment]
I don't think you need to install Pyvo explicitly. They fixed it this morning. Just wheel, then setuptools then exotic on separate lines.

**Comment by jpl-jengelke** [comment]
I would also do a version check for Python 3.8 and above, but we can add that later along with some other stuff.

**Comment by jpl-jengelke** [comment]
The Windows one won't work. Change the name to `.bat` and replace the first line with `ECHO OFF`

**Comment by rzellem** [comment]
> The Windows one won't work. Change the name to `.bat` and replace the first line with `ECHO OFF`

Done. How's this?

**Review by jpl-jengelke — APPROVED** [review]

**Pull request merged**
